### ISSUE TITLE
Go 1.11 was released with module support

### ISSUE THREAD

**Issue by ndbroadbent** [pwaller/docker-show-context#10]
Hello, I'm trying to use the latest version of `docker-show-context`, but I'm not super familiar with vgo and the new module support in Go. I tried installing `vgo` on an older Go version, which failed, and then I upgraded Go and saw that it is now 1.11, so maybe vgo isn't required anymore?

I'm still not really sure what I'm doing, so would it be possible to update the README with this new information?

**Comment by pwaller** [comment]
I've updated the readme. Please let me know if that doesn't fix the issue.

**Comment by ndbroadbent** [comment]
Awesome, thanks! I got it working, and it was really easy to find the file
I was accidentally including. Thanks for building this!

**Comment by pwaller** [comment]
Would you be able to share your mistake, in case others hit it too? Including error messages, so that it can be searched for?

**Comment by ndbroadbent** [comment]
Sure, when running `go get golang.org/x/vgo` on Go 1.9, I was getting this error message:

```
$ go get golang.org/x/vgo
# golang.org/x/vgo/vendor/cmd/go/internal/base
../go/src/golang.org/x/vgo/vendor/cmd/go/internal/base/goflags.go:132:23: flags.Output undefined (type flag.FlagSet has no field or method Output, but does have flag.output)
../go/src/golang.org/x/vgo/vendor/cmd/go/internal/base/goflags.go:137:23: flags.Output undefined (type flag.FlagSet has no field or method Output, but does have flag.output)
../go/src/golang.org/x/vgo/vendor/cmd/go/internal/base/goflags.go:143:22: flags.Output undefined (type flag.FlagSet has no field or method Output, but does have flag.output)
../go/src/golang.org/x/vgo/vendor/cmd/go/internal/base/goflags.go:147:22: flags.Output undefined (type flag.FlagSet has no field or method Output, but does have flag.output)
# golang.org/x/vgo/vendor/cmd/go/internal/modfetch/codehost
../go/src/golang.org/x/vgo/vendor/cmd/go/internal/modfetch/codehost/codehost.go:221:15: undefined: strings.Builder
```

But after I updated to Go `1.11`, I was able to run that command use `vgo` to install the dependencies. Thanks for the tip about `GO111MODULE=on go install -v`, it's great that you can do that now.
