### ISSUE TITLE
go install fails with "invalid pseudo-version"

### ISSUE THREAD

**Issue by golddranks** [pwaller/docker-show-context#14]
Doing `go install` as suggested brings up a weird error message:
```
env GO111MODULE=on go install -v
go: github.com/docker/docker@v0.0.0-0.20190115220918-5ec31380a5d3: invalid pseudo-version: version before v0.0.0 would have negative patch number
```

My go version is:
```
go version go1.13.4 darwin/amd64
```

Have you seen this error before? Any clues why it is happening?

**Comment by pwaller** [comment]
I wasn't able to reproduce the issue on go1.13.3.

I've updated the go.mod in 0aad35647cbab6f571486d001bf98d933280f862.

Hopefully that fixes things. If not, please report back and I will reopen this issue.
