### ISSUE TITLE
Setup instructions not working

### ISSUE THREAD

**Issue by nicbou** [pwaller/docker-show-context#2]
I get the following output when running the instructions on OS X:

```
github.com/pwaller/docker-show-context (download)
github.com/pwaller/docker-show-context/vendor/github.com/docker/docker (download)
package github.com/pwaller/docker-show-context/vendor/github.com/docker/docker/builder/dockerignore: /Users/********/go/src/github.com/pwaller/docker-show-context/vendor/github.com/docker/docker/.git exists but is not a directory
github.com/pwaller/docker-show-context/vendor/github.com/Sirupsen/logrus (download)
package github.com/pwaller/docker-show-context/vendor/github.com/Sirupsen/logrus: /Users/********/go/src/github.com/pwaller/docker-show-context/vendor/github.com/Sirupsen/logrus/.git exists but is not a directory
github.com/pwaller/docker-show-context/vendor/golang.org/x/net (download)
package github.com/pwaller/docker-show-context/vendor/golang.org/x/net/context: /Users/********/go/src/github.com/pwaller/docker-show-context/vendor/golang.org/x/net/.git exists but is not a directory
```

**Comment by pwaller** [comment]
What version of `git` and what version of `go` do you have?

**Comment by pwaller** [comment]
Detail about the failure: The referenced files are git submodules. These should be automatically put in place by `go get` as of go 1.7, if I remember correctly. If they're not, then something has gone wrong with go/git/your environment.

One potential fix is to try running `git submodule update --init` from `$GOPATH/github.com/pwaller/docker-show-context`. Please try this and report back.

**Comment by pwaller** [comment]
I'm going to presume you figured this out. If not, please shout on this issue again.

**Comment by nicbou** [comment]
Yes, in the end it was a path issue. It was my first exposure to Go, so I was not familiar with the beginner issues. Thanks a lot for your help!

**Comment by pwaller** [comment]
No problem. In return, may I ask what version of Go you have, and what resolution you came to?

Please could you explain the path issue so that others if they stumble upon this can fix it as you did?

**Comment by nicbou** [comment]
I installed Go on OS X with Homebrew. My current version is `go1.8.3 darwin/amd64`.

The complete fix as I remember it was to install @ddollar's fork, which installed without any issues, then to update my GOPATH so the command is directly callable.

In other words, it's possible that the changes made by ddollar fixed the issue described in this ticket, but it's also possible that the GOPATH update would have been enough.

**Comment by RobbieClarken** [comment]
Hi @pwaller - I've found this tool incredibly useful, thank you. I recently went to reinstall it on a new mac with Go v1.10.2 installed via homebrew and encountered a similar issue to nicbou:

<details>

<summary><em>Error message from <code>go get -v -u github.com/pwaller/docker-show-context</code></em></summary>

```
$ go get -v -u github.com/pwaller/docker-show-context
github.com/pwaller/docker-show-context (download)
github.com/pwaller/docker-show-context/vendor/github.com/docker/docker (download)
# cd /Users/clarkr/Developer/Go/src/github.com/pwaller/docker-show-context/vendor/github.com/docker/docker; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to rebase against.
See git-pull(1) for details.

    git pull <remote> <branch>

package github.com/pwaller/docker-show-context/vendor/github.com/docker/docker/builder/dockerignore: exit status 1
github.com/pwaller/docker-show-context/vendor/github.com/Sirupsen/logrus (download)
# cd /Users/clarkr/Developer/Go/src/github.com/pwaller/docker-show-context/vendor/github.com/Sirupsen/logrus; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to rebase against.
See git-pull(1) for details.

    git pull <remote> <branch>

package github.com/pwaller/docker-show-context/vendor/github.com/Sirupsen/logrus: exit status 1
github.com/pwaller/docker-show-context/vendor/golang.org/x/net (download)
# cd /Users/clarkr/Developer/Go/src/github.com/pwaller/docker-show-context/vendor/golang.org/x/net; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to rebase against.
See git-pull(1) for details.

    git pull <remote> <branch>

package github.com/pwaller/docker-show-context/vendor/golang.org/x/net/context: exit status 1
```

</details>

<br/>

I tried your suggestion of running `git submodule update --init` in the `$GOPATH/src/github.com/pwaller/docker-show-context` directory but the submodules seem to be checked out to the right commit so the command does nothing. Running the `go get [...]` command afterwards produces the same error as above.

I tried [@ddollar's fork](https://github.com/ddollar/docker-show-context), as mentioned by nicbou, and that worked. Perhaps you could pull in his change?

**Comment by pwaller** [comment]
Thanks for the message @RobbieClarken. Your issue looks unrelated, could you file a new one?

With respect to pulling @ddollar's changes, it surprises me that it worked for you, I would have expected things to diverge too much for pulling in random versions to work. I'm reluctant to pull his changes without further explanation as to why it was done and why it works.

FWIW, I'm also having an issue building it, please see #4. That seems to be yet a different issue from yours, but maybe fixing one will fix both.
