### ISSUE TITLE
It seems it would be very useful if this took the current .dockerignore into account

### ISSUE THREAD

**Issue by richtera** [pwaller/docker-show-context#3]
Otherwise you will always get the top 10 offenders to be things you've already excluded using dockerignore. I would like to hone in on the best choices in dockerignore.

**Comment by pwaller** [comment]
Ah, interesting if this is not already the case! Patches very welcome if you want to work on it, please announce on this thread.

**Comment by yciabaud** [comment]
I confirm this is not using `.dockerignore` and this less useful than I expected it to be :)

**Comment by pwaller** [comment]
I see the problem here. `.dockerignore` is taken into account, but the messaging is confusing. I have a fix inbound.
